option(BUILD_TESTS "Build test apps" ON)
option(SUPPORT_TIMER_FD_WITH_POLL "Use timerfd instead of posix timer" OFF)
option(BUILD_SOCKET_EXAMPLE_APP "Build example app for socket com" ON)
option(BUILD_SHELL_EXAMPLE_APP "Build example app for ncurse base shell" OFF)
option(BUILD_CURL_EXAMPLE_APP "Build example app for curl http request" ON)
option(BUILD_VIRTUAL_ADDR_EXAMPLE_APP "Build example app for virtual pagesize" ON)
set(${PROJECT_NAME}_VERSION_MAJOR 1)
set(${PROJECT_NAME}_VERSION_MINOR 0)
set(${PROJECT_NAME}_VERSION_PATCH 0)
set(${PROJECT_NAME}_LOG_BUFFER_SIZE 4096)