#ifndef ABSTRACT_CONFIG_H
#define ABSTRACT_CONFIG_H
/* #define USE_SYSLOG */
#define VERSION_MAJOR    1
#define VERSION_MINOR    0
#define VERSION_REVISION 0
#define LOG_BUFFER_SIZE 4096
#endif /*BASE_CONFIG_H*/
