name: Compile check
on: [push, pull_request]

jobs:
    Compile_source:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Compile source
          run: |
            mkdir build
            cd build
            cmake ..
            make
