name: cpplint
on: [push]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
    - name: "Lint check"
      id: lint_check
      run: |
        pip install cpplint
        cpplint --recursive --exclude=third_party/* --exclude=build/* --linelength=200 --filter=${lint_filter} .
      continue-on-error: true
    - name: "Exit success"
      id: exit_success
      run: exit 0