name: cpplint
on: [push]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
    - run: pip install cpplint
    - run: cpplint --recursive --exclude=third_party/* --linelength=200 "-readability/braces\
        ,-whitespace/braces\
        ,-whitespace/comments\
        ,-whitespace/indent\
        ,-whitespace/newline\
        ,-whitespace/operators\
        ,-whitespace/parens\
        " .